### ISSUE TITLE
Using BayeshERG

### ISSUE THREAD

**Issue by rra082** [GIST-CSBL/BayeshERG#2]
I have followed all your assigned instruction for conda install but it does not work and 
the 'dgl' module does not work or does not install properly any suggestion ?

**Comment by sunset222** [comment]
Hi, 
I am sorry for the inconvenience. 
Can you give me more detail of the errors that you experienced?

**Comment by sunset222** [comment]
I found the dependency installation issues while reproducing and it is resolved by installation with the environment.yml file. 
Please refer again to the Readme file.  
Again sorry for the inconvenience.
